### PR TITLE
Update photog

### PR DESCRIPTION
**Pull request by konrul**
* Adds auto-rotation for thumbnails if exif info is available
* Fixes thumbnail sizes to rely on heights not widths

### CODE REVIEW

**Comment by JaapJoris** [comment]
Thanks, but if the image lacks EXIF rotation information the thumbnail would fail with your patch.

Are you having issues with rotated images? All my Lightroom exported images are always in the correct orientation.

I wish all image files would simply start at the top left pixel, that would make writing image manipulation scripts a easier

**Comment by konrul** [comment]
> Thanks, but if the image lacks EXIF rotation information the thumbnail would fail with your patch.

Really? I thought it should work. I will test that. Thanks.

> Are you having issues with rotated images? All my Lightroom exported images are always in the correct orientation.

Yes, all of my non landscape images come out wrong :(
Does Lightroom do a physical transform?

> I wish all image files would simply start at the top left pixel, that would make writing image manipulation scripts a easier

Me too :)

**Comment by konrul** [comment]
> Thanks, but if the image lacks EXIF rotation information the thumbnail would fail with your patch.

I took a rotated photo, and ran:

`mogrify -strip photo.jpg`

The gallery was generated okay. Did you see a missing thumbnail?

**Comment by JaapJoris** [comment]
[The latest release of Photog!](https://pypi.org/project/photog/3.0.0/) now requires Exif information for all images, so this PR can be closed.

**Pull request closed without merging**
